import type { DemoStudent } from '../demoData';
import { NP, goldTextStyle, printAdjust } from '../tokens';
import { goldRule } from './shared';

interface Props {
  student: DemoStudent;
  forPrint?: boolean;
}

export default function FeedbackEnglishPage({ student, forPrint }: Props) {
  const father = student.fatherName.split(' ')[0];
  const mother = student.motherName.split(' ')[0];

  return (
    <div style={{
      width: NP.PAGE_W, height: NP.PAGE_H,
      background: NP.navyDark,
      boxSizing: 'border-box',
      padding: '32px 28px',
      display: 'flex',
      flexDirection: 'column',
      ...printAdjust(forPrint),
    }}>
      <div style={{ textAlign: 'center', fontSize: 16, color: NP.gold, marginBottom: 6 }}>✦</div>
      <div style={{ ...goldRule('100%', forPrint), height: 0.5 }} />
      <div style={{
        fontFamily: "'Poppins', sans-serif", fontSize: 7, color: NP.gold, textAlign: 'center',
        textTransform: 'uppercase', letterSpacing: '0.15em', marginTop: 10,
      }}>
        A Note From NeuraLife
      </div>

      <div style={{
        fontFamily: "'Playfair Display', serif", fontWeight: 800, fontSize: 18, textAlign: 'center',
        marginTop: 20, ...goldTextStyle(forPrint),
      }}>
        "We saw your child."
      </div>

      <div style={{ flex: 1, overflow: 'hidden', marginTop: 20 }}>
        <p style={{
          fontFamily: "'Poppins', sans-serif", fontWeight: 600, fontSize: 11, color: 'white', margin: '0 0 14px',
        }}>
          Dear {father} & {mother} Garu,
        </p>
        <p style={{ fontFamily: "'Lora', serif", fontSize: 10.5, color: 'white', lineHeight: 2.0, margin: '0 0 14px' }}>
          We did not meet {student.firstName} in person. We met him in data.
          And data — when you look at it long enough and with
          enough care — tells you everything.
        </p>
        <p style={{ fontFamily: "'Lora', serif", fontSize: 10.5, color: 'white', lineHeight: 2.0, margin: '0 0 14px' }}>
          We did not assess {student.firstName} on marks alone. We assessed him
          on every concept he struggled with and eventually
          understood. On the weeks he came in tired but still
          submitted homework. On the subjects that felt unfair
          but improved anyway.
        </p>
        <p style={{ fontFamily: "'Lora', serif", fontSize: 10.5, color: 'white', lineHeight: 2.0, margin: '0 0 14px' }}>
          {student.firstName}'s attendance was {student.attendanceRate}% over four years — he was
          present for {student.cl10Highlights.attendanceDaysPresent} of {student.cl10Highlights.totalSchoolDays} school days. That consistency
          is not in any marksheet. It is in us. We saw it.
        </p>
        <p style={{ fontFamily: "'Lora', serif", fontSize: 10.5, color: 'white', lineHeight: 2.0, margin: '0 0 14px' }}>
          Mathematics went from 68% to 84%. That kind of growth
          does not happen in an exam hall. It happens in the
          quiet moments before one — and your son lived those
          moments.
        </p>
        <p style={{ fontFamily: "'Lora', serif", fontSize: 10.5, color: 'white', lineHeight: 2.0, margin: 0 }}>
          Trust your son. He has already shown you what he is
          capable of.
        </p>
      </div>

      <div>
        <div style={{ ...goldRule(100, forPrint), marginBottom: 16 }} />
        <p style={{ fontFamily: "'Lora', serif", fontStyle: 'italic', fontSize: 10, color: NP.gold, margin: 0 }}>
          With respect and pride,
        </p>
        <div style={{ width: 80, height: 1, background: NP.gold, margin: '6px 0' }} />
        <p style={{ fontFamily: "'Lora', serif", fontStyle: 'italic', fontSize: 10, color: NP.gold, margin: 0 }}>
          The NeuraLife Team
        </p>
        <p style={{ fontFamily: "'Lora', serif", fontStyle: 'italic', fontSize: 10, color: NP.gold, margin: 0 }}>
          Visakhapatnam, Andhra Pradesh
        </p>
      </div>

      <div style={{ borderTop: '1px solid rgba(212,168,67,0.2)', marginTop: 16, paddingTop: 10 }}>
        <div style={{ ...goldRule('100%', forPrint), marginBottom: 8 }} />
        <p style={{
          fontFamily: "'Poppins', sans-serif", fontSize: 7, color: 'rgba(255,255,255,0.4)',
          textAlign: 'center', lineHeight: 1.5, margin: 0,
        }}>
          This letter was generated by NeuraLife AI from<br />
          {student.firstName}'s verified academic record.
        </p>
      </div>
    </div>
  );
}
